### ISSUE TITLE
Running for a custom testnet (or Holesky) - settings to change?

### ISSUE THREAD

**Issue by rocknet** [ethstakersclub/ethstakersclub#14]
Hi.  I'm getting closer to having this running for a custom testnet.  I'm using docker compose for postgres and redis, those services are working fine, it seems.

The issue I'm having now is I'm trying to sync and I'm getting strange errors where it looks like it's trying to sync from block -60 to 0 to start.  Eventually -60 becomes -61.  I'm guessing the -60 comes from a bad setting in settings.py.  What I'm doing is taking the MIN_GENESIS_TIME from consensus config.yaml, and setting that to GENESIS_TIMESTAMP in settings.py.  I know that's not quite right because I'm also using a 5 minute GENESIS_DELAY, but I'm not sure where it's getting -60 as the start block.

```
[2023-08-24 22:20:28,244: WARNING/ForkPoolWorker-19] An error occurred while processing the deposits from block -60 to 0.
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 64, in get_deposits_task
    get_deposits(fromBlock, toBlock)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 632, in get_deposits
    deposit_filter = deposit_contract.events.DepositEvent.create_filter(fromBlock=fromBlock, toBlock=toBlock)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/eth_utils/decorators.py", line 20, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/web3/contract/contract.py", line 229, in create_filter
    log_filter = filter_builder.deploy(self.w3)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/web3/_utils/events.py", line 439, in deploy
    log_filter = cast("LogFilter", w3.eth.filter(self.filter_params))
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/web3/manager.py", line 205, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'invalid argument 0: hex string without 0x prefix'}
```

Also, I'm using Lodestar as my BN client, do you think there might be an incompatibility?
I'm also seeing logs like this:
```
[2023-08-24 22:20:28,886: INFO/ForkPoolWorker-19] Process block at slot 8: {'data': {'message': {'slot': '8', 'proposer_index': '4', 'parent_root': '0x5e13b7a5495cac97ee5872504f3854432a1c3279453b8ca6df1c0aa28410c2e4', 'state_root': '0x9be65237d8508dac8b08edf16c0f039a2882e657
[2023-08-24 22:20:28,891: WARNING/ForkPoolWorker-19] An error occurred processing the slot 8.
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 36, in load_block_task
    load_block(slot, epoch)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 482, in load_block
    raise Exception("AttestationCommittee missing")
Exception: AttestationCommittee missing
```

The settings I've changed are: GENESIS_TIMESTAMP, MERGE_SLOT (0), ALTAIR_EPOCH (0), DEPOSIT_CONTRACT_DEPLOYMENT_BLOCK (0), and the DEPOSIT_CONTRACT_ADDRESS.

As background on what I'm doing, I've adapted [Afri's article](https://dev.to/q9/how-to-merge-an-ethereum-network-right-from-the-genesis-block-3454) on standing up a post-merge testnet from genesis, in fact, it's post shapella.  The blockchain is running fine, it's finalizing and everything, was just hoping to get a BN explorer running.  I've done all of this in docker compose.  If I get this running, I can share back some docker compose goodness to help get ethstakersclub running.  

If you're curious what I've got going, it's here: https://github.com/rocknet/ethiab.  To run entirely locally, just set ENABLE_EXTERNAL_DISCOVERY to false, that'll add just 8 validators on the boot node.  

Happy to take this troubleshooting off Github if that helps.  Thanks in advance for any ideas.

**Comment by rocknet** [comment]
Ah, probably this: https://github.com/ethstakersclub/ethstakersclub/blob/e35883e90ae12c10c0ae96535ff2fa75ec74c6b0/blockfetcher/management/commands/block_listener.py#L132C5-L132C83.  

Have you considered deposit contract deployments that happen at genesis?  This is how Holesky is going to work anyway, so we should probably get to the bottom of it.

**Comment by ethstakersclub** [comment]
I created a new branch with some changes that might fix at least some of those issues. However, I haven't had the opportunity to verify these changes yet.

Before you proceed with merging these changes, it's best to reset the database and purge all ongoing celery tasks using the following command:

```bash
celery -A ethstakersclub purge
```

By the way, I hope I didn't misunderstand you, but we would obviously greatly appreciate your assistance in testing it for the Holesky testnet. I believe that running it for the Holesky testnet would also be quite cheap. Considering that storage is not a major issue (<200GB), opting for the least expensive server at around 5.99€ should suffice more than easily.

**Comment by rocknet** [comment]
Great, thanks. I’ll check this out after work / this weekend.

**Comment by rocknet** [comment]
Hi there.  So, I still have errors in the celery worker.  The block_listener doesn't throw anymore, but it also doesn't see any validators it seems.

On my quick investigation, one problem seems to be around here: https://github.com/ethstakersclub/ethstakersclub/blob/e35883e90ae12c10c0ae96535ff2fa75ec74c6b0/blockfetcher/management/commands/block_listener.py#L250C25-L267C25

We should probably look for any instances of subtracting from a slot or epoch index.

This might also be problematic for example:
https://github.com/ethstakersclub/ethstakersclub/blob/da0aa8890760f4463d8178260b1ef97afd0ab5d1/blockfetcher/management/commands/block_listener.py#L219C5-L220C52

Example celery log:
```
[2023-08-25 21:32:37,328: WARNING/ForkPoolWorker-27] An error occurred while processing the epoch rewards for epoch -1.
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 54, in load_epoch_rewards_task
    load_epoch_rewards(epoch)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 517, in load_epoch_rewards
    for sync_reward in sync_rewards_json["data"]:
KeyError: 'data'
```

There are other error logs, but I suspect it's because the data is not loaded into the db.

```
[2023-08-25 21:32:38,210: INFO/ForkPoolWorker-27] Process block at slot 16: {'data': {'message': {'slot': '16', 'proposer_index': '5', 'parent_root': '0xf0075bd3d057927a26ba86dcb00ed38f5e3f45ba6dfc2bb4fbc326c4c2bef0b0', 'state_root': '0x8d82bb8be69d4955a92769915a2c9fa16777e1f
[2023-08-25 21:32:38,216: WARNING/ForkPoolWorker-27] An error occurred processing the slot 16.
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 36, in load_block_task
    load_block(slot, epoch)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 468, in load_block
    raise Exception("AttestationCommittee missing")
Exception: AttestationCommittee missing
```

Logs from block_listener (no exceptions, but doesn't look like it's working properly)
```
[2023-08-25 21:18:28] INFO: syncing last_slot_processed=0 loop_epoch=0 reorg=False
[2023-08-25 21:18:28] INFO: Head is slot=0 epoch=0 block=0
[2023-08-25 21:18:28] INFO: Setup validators
[2023-08-25 21:18:29] INFO: Started up: filling epochs
[2023-08-25 21:18:29] INFO: Staking deposit blocks processed: 0
[2023-08-25 21:18:41] INFO: syncing last_slot_processed=1 loop_epoch=0 reorg=False
[2023-08-25 21:18:41] INFO: Head is slot=2 epoch=0 block=1
[2023-08-25 21:18:41] INFO: Staking deposit blocks processed: 0
[2023-08-25 21:18:53] INFO: syncing last_slot_processed=3 loop_epoch=0 reorg=False
[2023-08-25 21:18:53] INFO: Head is slot=3 epoch=0 block=2
[2023-08-25 21:18:53] INFO: Staking deposit blocks processed: 0
```

Thanks for your time so far.

**Comment by ethstakersclub** [comment]
Thanks a lot for your help so far. I really appreciate it.

I believe I've gained a better grasp of the issue at hand. It appears that the initial epoch isn't being processed, leading to a missed AttestationCommittee. This situation seems to arise from starting the sync from an entirely new chain, causing the explorer to run from slot 0 onward. Consequently, the `setup_epochs` function fails to process any epoch at startup since the finalized epoch is either 0 or potentially undefined.

While the latest commit might be able to fix this, its not guaranteed. It seems like I have to setup a custom chain now. :)

**Comment by ethstakersclub** [comment]
We've got it working now with a local testnet. Please let me know if it's working with your client configuration as well.

When pulling the changes, you now have to add this line to your settings.py.
```python
MIN_PER_EPOCH_CHURN_LIMIT = 4
```

**Comment by rocknet** [comment]
Now getting this error:
```
[2023-08-26 15:40:00] INFO: Head is slot=2 epoch=0 block=2
[2023-08-26 15:40:00] INFO: Setup validators
[2023-08-26 15:40:01] INFO: set up new sync committee for slot 0 epoch -1
[2023-08-26 15:40:01] INFO: sync committee after altair, proceeding
Traceback (most recent call last):
  File "/root/ethstakersclub/manage.py", line 22, in <module>
    main()
  File "/root/ethstakersclub/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/root/ethstakersclub/blockfetcher/management/commands/block_listener.py", line 329, in handle
    last_slot_processed, loop_epoch, last_balance_update_time = sync_up(main_row)
  File "/root/ethstakersclub/blockfetcher/management/commands/block_listener.py", line 204, in sync_up
    create_sync_committee(loop_epoch - 256)
  File "/root/ethstakersclub/blockfetcher/management/commands/block_listener.py", line 73, in create_sync_committee
    sync_validators = [int(s) for s in sync_committee_state["data"]["validators"]]
TypeError: list indices must be integers or slices, not str
```

Looks like it's set on epoch -1 for some reason.

Do you have discord?  Might be easier to work through this a bit more interactively.

**Comment by ethstakersclub** [comment]
I'm a bit confused as to why this didn't happen to our local node. Maybe it has something to do with the beacon client response?

Anyway, we've added a check to ensure that this doesn't happen anymore.

We can of course also use discord if you've got time to debug this.

**Comment by rocknet** [comment]
Ok, it looks better now, but I still have some questions.  Yeah, let's connect on discord.  My user id is 368446312800190464.  Not sure if you have your own server running or if you want to just DM, either is fine.

You know bloxroute ethical shut down right?  
 Message: 'An error occurred (https://bloxroute.ethical.blxrbdn.com):'

**Comment by rocknet** [comment]
I happened to shut down the block listener and then tried to restart it, got this:

```
[2023-08-26 16:35:54] INFO: New epoch 0
[2023-08-26 16:35:54] ERROR: 'dependent_root'
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/management/commands/block_listener.py", line 246, in sync_up
    load_epoch(check_epoch, slot)
  File "/root/.venv/ethstakersclub/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 649, in load_epoch
    defaults={'dependent_root': epoch_proposer["dependent_root"],
KeyError: 'dependent_root'
```

It repeats ad infinitum

**Comment by rocknet** [comment]
Also seeing this error:

```
[2023-08-26 16:44:49,859: WARNING/ForkPoolWorker-8] An error occurred while updating the validators 0.
Traceback (most recent call last):
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 101, in make_balance_snapshot_task
    make_balance_snapshot(slot, timestamp)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/ethstakersclub/blockfetcher/tasks.py", line 171, in make_balance_snapshot
    highest_block_at_date = Block.objects.filter(slot_number__lte=highest_slot_at_date, empty=0).order_by('-slot_number').first().block_number
AttributeError: 'NoneType' object has no attribute 'block_number'
```

It looks like it's mostly running ok though.  Will check out the api.  As I'm running this in a docker container and not exposing HTTP yet, I need to test using the api first.

**Comment by ethstakersclub** [comment]
Thats's really weird. Anyway, I somehow can't invite you on discord. Maybe has something to do with privacy settings? So here is a link to join https://discord.gg/AzvT7nt

**Comment by ethstakersclub** [comment]
> Ok, it looks better now, but I still have some questions. Yeah, let's connect on discord. My user id is 368446312800190464. Not sure if you have your own server running or if you want to just DM, either is fine.
> 
> You know bloxroute ethical shut down right? Message: 'An error occurred (https://bloxroute.ethical.blxrbdn.com):'

I really wonder about the preservation of information on their blocks. Perhaps there's a backup solution available somewhere?
