### ISSUE TITLE
Cannot use None as a query value

### ISSUE THREAD

**Issue by michaelbarbas** [ethstakersclub/ethstakersclub#20]
At line 222 in [blockfetcher/tasks.py](https://github.com/ethstakersclub/ethstakersclub/blob/main/blockfetcher/tasks.py#L222C5-L222C21). I receive an error saying I cannot use None as a query value. 

I have noticed at [L189](https://github.com/ethstakersclub/ethstakersclub/blob/main/blockfetcher/tasks.py#L189), my `highest_block_at_date` variable gets set to None, but `highest_slot_at_date` assigns properly. I have followed the setup instructions in the documentation and it does not seem to be progressing past this point. Any idea what is going on? Thanks

```
[2024-01-11 16:18:24,920: WARNING/ForkPoolWorker-2698] An error occurred while updating the validators 2419456.
Traceback (most recent call last):
  File "/home/ubuntu/indexer/ethstakersclub/blockfetcher/tasks.py", line 110, in make_balance_snapshot_task
    make_balance_snapshot(slot, timestamp)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/indexer/ethstakersclub/blockfetcher/tasks.py", line 225, in make_balance_snapshot
    total_deposited = StakingDeposit.objects.filter(block_number__lt=highest_block_at_date).values('validator_id').annotate(deposit_total=Sum('amount'))
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/ubuntu/indexer/ethstakersclub/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1280, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

**Comment by michaelbarbas** [comment]
Looking more into it im seeing this query done when filtering the objects.

`SELECT "blockfetcher_block"."proposer", "blockfetcher_block"."block_number", "blockfetcher_block"."slot_number", "blockfetcher_block"."block_hash", "blockfetcher_block"."parent_root", "blockfetcher_block"."state_root", "blockfetcher_block"."block_root", "blockfetcher_block"."fee_recipient", "blockfetcher_block"."timestamp", "blockfetcher_block"."parent_hash", "blockfetcher_block"."epoch", "blockfetcher_block"."deposit_count", "blockfetcher_block"."voluntary_exit_count", "blockfetcher_block"."block_transfer_count", "blockfetcher_block"."total_reward", "blockfetcher_block"."mev_reward", "blockfetcher_block"."fee_reward", "blockfetcher_block"."mev_boost_relay", "blockfetcher_block"."mev_reward_recipient", "blockfetcher_block"."burnt_fee", "blockfetcher_block"."total_tx_fee", "blockfetcher_block"."transaction_count", "blockfetcher_block"."sync_committee_bits", "blockfetcher_block"."sync_committee_signature", "blockfetcher_block"."randao_reveal", "blockfetcher_block"."graffiti", "blockfetcher_block"."signature", "blockfetcher_block"."empty" FROM "blockfetcher_block" WHERE ("blockfetcher_block"."empty" = 0 AND "blockfetcher_block"."slot_number" <= 3063599) ORDER BY "blockfetcher_block"."slot_number" DESC`

but `blockfetcher_block` has a null value for column `block_number` for every row. I believe this is the cause. Is the block number supposed to be populated in the database before the snapshot balance is made?
